In [5]:
import math
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings("ignore")

## Модуль A. Предобработка больших данных
###  ЗАГРУЗКА ДАННЫХ
#### Данные загружены. Представлен код по загрузке, отражено в отчете. Результаты очищены от технической информации (если обнаружено), отражено в отчете.

In [2]:
bsm_data = pd.read_csv('data/brooklyn_sales_map.csv')

In [3]:
pd.set_option('display.max_columns', None)
bsm_data.head(5)

,Unnamed: 0,borough,neighborhood,building_class_category,tax_class,block,lot,easement,building_class,address,apartment_number,zip_code,residential_units,commercial_units,total_units,land_sqft,gross_sqft,year_built,tax_class_at_sale,building_class_at_sale,sale_price,sale_date,year_of_sale,Borough,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,PolicePrct,HealthCent,HealthArea,SanitBoro,SanitDistr,SanitSub,Address,ZoneDist1,ZoneDist2,ZoneDist3,ZoneDist4,Overlay1,Overlay2,SPDist1,SPDist2,SPDist3,LtdHeight,SplitZone,BldgClass,LandUse,Easements,OwnerType,OwnerName,LotArea,BldgArea,ComArea,ResArea,OfficeArea,RetailArea,GarageArea,StrgeArea,FactryArea,OtherArea,AreaSource,NumBldgs,NumFloors,UnitsRes,UnitsTotal,LotFront,LotDepth,BldgFront,BldgDepth,Ext,ProxCode,IrrLotCode,LotType,BsmtCode,AssessLand,AssessTot,ExemptLand,ExemptTot,YearBuilt,YearAlter1,YearAlter2,HistDist,Landmark,BuiltFAR,ResidFAR,CommFAR,FacilFAR,BoroCode,BBL,CondoNo,Tract2010,XCoord,YCoord,ZoneMap,ZMCode,Sanborn,TaxMap,EDesigNum,APPBBL,APPDate,PLUTOMapID,FIRM07_FLA,PFIRM15_FL,Version,MAPPLUTO_F,SHAPE_Leng,SHAPE_Area
0,1,3,DOWNTOWN-METROTECH,28 COMMERCIAL CONDOS,4,140,1001,NaN,R5,330 JAY STREET,COURT,11201,0,1,1,0.0,0.0,2002,4,R5,499401179.0,2008-04-23,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,3,DOWNTOWN-FULTON FERRY,29 COMMERCIAL GARAGES,4,54,1,NaN,G7,85 JAY STREET,NaN,11201,0,0,0,134988.0,0.0,0,4,G7,345000000.0,2016-12-20,2016,BK,302.0,21.00,3017.0,13.0,33.0,11201.0,L118,84.0,36.0,1000.0,3.0,2.0,1B,87 JAY STREET,M1-2/R8,NaN,NaN,NaN,NaN,NaN,MX-2,NaN,NaN,NaN,N,G7,10.0,0.0,P,85 JAY STREET BROOKLY,134988.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,490.50,275.33,0.0,0.00,NaN,0.0,N,5.0,5.0,1571850.0,1571850.0,1571850.0,1571850.0,0.0,0.0,0.0,NaN,NaN,0.00,7.20,2.0,6.5,3.0,3.000540e+09,0.0,21.0,988208.0,195011.0,12d,NaN,302 016,30101.0,NaN,3.000540e+09,12/06/2002,1.0,NaN,NaN,17V1.1,0.0,1559.889144,140131.577176
2,3,3,BROOKLYN HEIGHTS,21 OFFICE BUILDINGS,4,204,1,NaN,O6,29 COLUMBIA HEIGHTS,NaN,11201,0,0,0,32000.0,304650.0,1924,4,O6,340000000.0,2016-08-03,2016,BK,302.0,1.00,1003.0,13.0,33.0,11201.0,E205,84.0,38.0,2300.0,3.0,2.0,1A,29 COLUMBIA HEIGHTS,M2-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,O6,5.0,0.0,NaN,25-30 COLUMBIA HEIGHT,32000.0,304650.0,304650.0,0.0,264750.0,0.0,0.0,0.0,0.0,39900.0,2.0,1.0,13.0,0.0,0.0,92.42,335.92,335.0,92.00,NaN,0.0,Y,3.0,5.0,1548000.0,25463250.0,0.0,0.0,1924.0,1980.0,0.0,NaN,NaN,9.52,0.00,2.0,0.0,3.0,3.002040e+09,0.0,1.0,985952.0,195007.0,12d,NaN,302 004,30106.0,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,890.718521,34656.447240
3,4,3,MILL BASIN,22 STORE BUILDINGS,4,8470,55,NaN,K6,5120 AVENUE U,NaN,11234,0,123,123,905000.0,2548000.0,1970,4,K6,276947000.0,2012-11-28,2012,BK,318.0,698.00,2005.0,22.0,46.0,11234.0,E323,63.0,35.0,8822.0,3.0,18.0,4E,5120 AVENUE U,M3-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,K6,5.0,1.0,NaN,BROOKLYN KINGS PLAZA,905000.0,2548000.0,2548000.0,0.0,0.0,1263000.0,1285000.0,0.0,0.0,0.0,2.0,4.0,2.0,0.0,123.0,930.00,859.00,0.0,0.00,NaN,0.0,Y,3.0,5.0,36532350.0,149792400.0,0.0,0.0,1970.0,0.0,0.0,NaN,NaN,2.82,0.00,2.0,0.0,3.0,3.084700e+09,0.0,698.0,1006597.0,161424.0,23b,NaN,319 077,32502.0,NaN,0.000000e+00,NaN,1.0,1.0,1.0,17V1.1,0.0,3729.786857,797554.847834
4,5,3,BROOKLYN HEIGHTS,26 OTHER HOTELS,4,230,1,NaN,H8,21 CLARK STREET,NaN,11201,0,1,1,20267.0,356000.0,1927,4,H8,202500000.0,2017-10-31,2017,BK,302.0,3.01,2000.0,13.0,33.0,11201.0,E205,84.0,38.0,2300.0,3.0,2.0,1A,79 WILLOW STREET,R6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LH-1,N,H8,8.0,0.0,X,WATCHTOWER C/O REAL P,20267.0,356000.0,30000.0,0.0,30000.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,15.0,0.0,1.0,202.00,100.33,202.0,100.33,NaN,0.0,N,3.0,2.0,2250000.0,27166050.0,2250000.0,27166050.0,1927.0,1998.0,2000.0,Brooklyn Heights Historic District,NaN,17.57,2.43,0.0,4.8,3.0,3.002300e+09,0.0,301.0,985622.0,193713.0,12d,NaN,302 014,30106.0,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,620.761169,21360.147631

In [5]:
bsm_data = bsm_data.drop(['Unnamed: 0',], axis=1)
bsm_data.head(5)

,borough,neighborhood,building_class_category,tax_class,block,lot,easement,building_class,address,apartment_number,zip_code,residential_units,commercial_units,total_units,land_sqft,gross_sqft,year_built,tax_class_at_sale,building_class_at_sale,sale_price,sale_date,year_of_sale,Borough,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,PolicePrct,HealthCent,HealthArea,SanitBoro,SanitDistr,SanitSub,Address,ZoneDist1,ZoneDist2,ZoneDist3,ZoneDist4,Overlay1,Overlay2,SPDist1,SPDist2,SPDist3,LtdHeight,SplitZone,BldgClass,LandUse,Easements,OwnerType,OwnerName,LotArea,BldgArea,ComArea,ResArea,OfficeArea,RetailArea,GarageArea,StrgeArea,FactryArea,OtherArea,AreaSource,NumBldgs,NumFloors,UnitsRes,UnitsTotal,LotFront,LotDepth,BldgFront,BldgDepth,Ext,ProxCode,IrrLotCode,LotType,BsmtCode,AssessLand,AssessTot,ExemptLand,ExemptTot,YearBuilt,YearAlter1,YearAlter2,HistDist,Landmark,BuiltFAR,ResidFAR,CommFAR,FacilFAR,BoroCode,BBL,CondoNo,Tract2010,XCoord,YCoord,ZoneMap,ZMCode,Sanborn,TaxMap,EDesigNum,APPBBL,APPDate,PLUTOMapID,FIRM07_FLA,PFIRM15_FL,Version,MAPPLUTO_F,SHAPE_Leng,SHAPE_Area
0,3,DOWNTOWN-METROTECH,28 COMMERCIAL CONDOS,4,140,1001,NaN,R5,330 JAY STREET,COURT,11201,0,1,1,0.0,0.0,2002,4,R5,499401179.0,2008-04-23,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,DOWNTOWN-FULTON FERRY,29 COMMERCIAL GARAGES,4,54,1,NaN,G7,85 JAY STREET,NaN,11201,0,0,0,134988.0,0.0,0,4,G7,345000000.0,2016-12-20,2016,BK,302.0,21.00,3017.0,13.0,33.0,11201.0,L118,84.0,36.0,1000.0,3.0,2.0,1B,87 JAY STREET,M1-2/R8,NaN,NaN,NaN,NaN,NaN,MX-2,NaN,NaN,NaN,N,G7,10.0,0.0,P,85 JAY STREET BROOKLY,134988.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,490.50,275.33,0.0,0.00,NaN,0.0,N,5.0,5.0,1571850.0,1571850.0,1571850.0,1571850.0,0.0,0.0,0.0,NaN,NaN,0.00,7.20,2.0,6.5,3.0,3.000540e+09,0.0,21.0,988208.0,195011.0,12d,NaN,302 016,30101.0,NaN,3.000540e+09,12/06/2002,1.0,NaN,NaN,17V1.1,0.0,1559.889144,140131.577176
2,3,BROOKLYN HEIGHTS,21 OFFICE BUILDINGS,4,204,1,NaN,O6,29 COLUMBIA HEIGHTS,NaN,11201,0,0,0,32000.0,304650.0,1924,4,O6,340000000.0,2016-08-03,2016,BK,302.0,1.00,1003.0,13.0,33.0,11201.0,E205,84.0,38.0,2300.0,3.0,2.0,1A,29 COLUMBIA HEIGHTS,M2-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,O6,5.0,0.0,NaN,25-30 COLUMBIA HEIGHT,32000.0,304650.0,304650.0,0.0,264750.0,0.0,0.0,0.0,0.0,39900.0,2.0,1.0,13.0,0.0,0.0,92.42,335.92,335.0,92.00,NaN,0.0,Y,3.0,5.0,1548000.0,25463250.0,0.0,0.0,1924.0,1980.0,0.0,NaN,NaN,9.52,0.00,2.0,0.0,3.0,3.002040e+09,0.0,1.0,985952.0,195007.0,12d,NaN,302 004,30106.0,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,890.718521,34656.447240
3,3,MILL BASIN,22 STORE BUILDINGS,4,8470,55,NaN,K6,5120 AVENUE U,NaN,11234,0,123,123,905000.0,2548000.0,1970,4,K6,276947000.0,2012-11-28,2012,BK,318.0,698.00,2005.0,22.0,46.0,11234.0,E323,63.0,35.0,8822.0,3.0,18.0,4E,5120 AVENUE U,M3-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,K6,5.0,1.0,NaN,BROOKLYN KINGS PLAZA,905000.0,2548000.0,2548000.0,0.0,0.0,1263000.0,1285000.0,0.0,0.0,0.0,2.0,4.0,2.0,0.0,123.0,930.00,859.00,0.0,0.00,NaN,0.0,Y,3.0,5.0,36532350.0,149792400.0,0.0,0.0,1970.0,0.0,0.0,NaN,NaN,2.82,0.00,2.0,0.0,3.0,3.084700e+09,0.0,698.0,1006597.0,161424.0,23b,NaN,319 077,32502.0,NaN,0.000000e+00,NaN,1.0,1.0,1.0,17V1.1,0.0,3729.786857,797554.847834
4,3,BROOKLYN HEIGHTS,26 OTHER HOTELS,4,230,1,NaN,H8,21 CLARK STREET,NaN,11201,0,1,1,20267.0,356000.0,1927,4,H8,202500000.0,2017-10-31,2017,BK,302.0,3.01,2000.0,13.0,33.0,11201.0,E205,84.0,38.0,2300.0,3.0,2.0,1A,79 WILLOW STREET,R6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LH-1,N,H8,8.0,0.0,X,WATCHTOWER C/O REAL P,20267.0,356000.0,30000.0,0.0,30000.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,15.0,0.0,1.0,202.00,100.33,202.0,100.33,NaN,0.0,N,3.0,2.0,2250000.0,27166050.0,2250000.0,27166050.0,1927.0,1998.0,2000.0,Brooklyn Heights Historic District,NaN,17.57,2.43,0.0,4.8,3.0,3.002300e+09,0.0,301.0,985622.0,193713.0,12d,NaN,302 014,30106.0,NaN,0.000000e+00,NaN,1.0,NaN,NaN,17V1.1,0.0,620.761169,21360.147631

### ПРЕДОБРАБОТКА ДАННЫХ
#### Необходимо проанализировать значения всех атрибутов датасета, проанализировать значения, которыми заполнены признаки и обработать их при необходимости, отразить в отчете.

In [6]:
#Удаление всех столбцов с количеством Nan больше 100к. Т.к. в базе данных 400к строк.
names = bsm_data.columns
deletee=[]
for i in range(bsm_data.shape[1]):
    if(bsm_data.isna().sum()[i]>=100000):
        print('Столбец ',i+1,') ',names[i],' удалён.', sep='')
        deletee.append(names[i])

bsm_data = bsm_data.drop(deletee, axis=1)
print('Столбцов осталось:',bsm_data.shape[1])

Столбец 7) easement удалён.
Столбец 10) apartment_number удалён.
Столбец 39) ZoneDist2 удалён.
Столбец 40) ZoneDist3 удалён.
Столбец 41) ZoneDist4 удалён.
Столбец 42) Overlay1 удалён.
Столбец 43) Overlay2 удалён.
Столбец 44) SPDist1 удалён.
Столбец 45) SPDist2 удалён.
Столбец 46) SPDist3 удалён.
Столбец 47) LtdHeight удалён.
Столбец 52) OwnerType удалён.
Столбец 73) Ext удалён.
Столбец 85) HistDist удалён.
Столбец 86) Landmark удалён.
Столбец 98) ZMCode удалён.
Столбец 101) EDesigNum удалён.
Столбец 103) APPDate удалён.
Столбец 105) FIRM07_FLA удалён.
Столбец 106) PFIRM15_FL удалён.
Столбцов осталось: 90

In [8]:
bsm_data.head(5)

,borough,neighborhood,building_class_category,tax_class,block,lot,building_class,address,zip_code,residential_units,commercial_units,total_units,land_sqft,gross_sqft,year_built,tax_class_at_sale,building_class_at_sale,sale_price,sale_date,year_of_sale,Borough,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,PolicePrct,HealthCent,HealthArea,SanitBoro,SanitDistr,SanitSub,Address,ZoneDist1,SplitZone,BldgClass,LandUse,Easements,OwnerName,LotArea,BldgArea,ComArea,ResArea,OfficeArea,RetailArea,GarageArea,StrgeArea,FactryArea,OtherArea,AreaSource,NumBldgs,NumFloors,UnitsRes,UnitsTotal,LotFront,LotDepth,BldgFront,BldgDepth,ProxCode,IrrLotCode,LotType,BsmtCode,AssessLand,AssessTot,ExemptLand,ExemptTot,YearBuilt,YearAlter1,YearAlter2,BuiltFAR,ResidFAR,CommFAR,FacilFAR,BoroCode,BBL,CondoNo,Tract2010,XCoord,YCoord,ZoneMap,Sanborn,TaxMap,APPBBL,PLUTOMapID,Version,MAPPLUTO_F,SHAPE_Leng,SHAPE_Area
0,3,DOWNTOWN-METROTECH,28 COMMERCIAL CONDOS,4,140,1001,R5,330 JAY STREET,11201,0,1,1,0.0,0.0,2002,4,R5,499401179.0,2008-04-23,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,DOWNTOWN-FULTON FERRY,29 COMMERCIAL GARAGES,4,54,1,G7,85 JAY STREET,11201,0,0,0,134988.0,0.0,0,4,G7,345000000.0,2016-12-20,2016,BK,302.0,21.00,3017.0,13.0,33.0,11201.0,L118,84.0,36.0,1000.0,3.0,2.0,1B,87 JAY STREET,M1-2/R8,N,G7,10.0,0.0,85 JAY STREET BROOKLY,134988.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,490.50,275.33,0.0,0.00,0.0,N,5.0,5.0,1571850.0,1571850.0,1571850.0,1571850.0,0.0,0.0,0.0,0.00,7.20,2.0,6.5,3.0,3.000540e+09,0.0,21.0,988208.0,195011.0,12d,302 016,30101.0,3.000540e+09,1.0,17V1.1,0.0,1559.889144,140131.577176
2,3,BROOKLYN HEIGHTS,21 OFFICE BUILDINGS,4,204,1,O6,29 COLUMBIA HEIGHTS,11201,0,0,0,32000.0,304650.0,1924,4,O6,340000000.0,2016-08-03,2016,BK,302.0,1.00,1003.0,13.0,33.0,11201.0,E205,84.0,38.0,2300.0,3.0,2.0,1A,29 COLUMBIA HEIGHTS,M2-1,N,O6,5.0,0.0,25-30 COLUMBIA HEIGHT,32000.0,304650.0,304650.0,0.0,264750.0,0.0,0.0,0.0,0.0,39900.0,2.0,1.0,13.0,0.0,0.0,92.42,335.92,335.0,92.00,0.0,Y,3.0,5.0,1548000.0,25463250.0,0.0,0.0,1924.0,1980.0,0.0,9.52,0.00,2.0,0.0,3.0,3.002040e+09,0.0,1.0,985952.0,195007.0,12d,302 004,30106.0,0.000000e+00,1.0,17V1.1,0.0,890.718521,34656.447240
3,3,MILL BASIN,22 STORE BUILDINGS,4,8470,55,K6,5120 AVENUE U,11234,0,123,123,905000.0,2548000.0,1970,4,K6,276947000.0,2012-11-28,2012,BK,318.0,698.00,2005.0,22.0,46.0,11234.0,E323,63.0,35.0,8822.0,3.0,18.0,4E,5120 AVENUE U,M3-1,N,K6,5.0,1.0,BROOKLYN KINGS PLAZA,905000.0,2548000.0,2548000.0,0.0,0.0,1263000.0,1285000.0,0.0,0.0,0.0,2.0,4.0,2.0,0.0,123.0,930.00,859.00,0.0,0.00,0.0,Y,3.0,5.0,36532350.0,149792400.0,0.0,0.0,1970.0,0.0,0.0,2.82,0.00,2.0,0.0,3.0,3.084700e+09,0.0,698.0,1006597.0,161424.0,23b,319 077,32502.0,0.000000e+00,1.0,17V1.1,0.0,3729.786857,797554.847834
4,3,BROOKLYN HEIGHTS,26 OTHER HOTELS,4,230,1,H8,21 CLARK STREET,11201,0,1,1,20267.0,356000.0,1927,4,H8,202500000.0,2017-10-31,2017,BK,302.0,3.01,2000.0,13.0,33.0,11201.0,E205,84.0,38.0,2300.0,3.0,2.0,1A,79 WILLOW STREET,R6,N,H8,8.0,0.0,WATCHTOWER C/O REAL P,20267.0,356000.0,30000.0,0.0,30000.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,15.0,0.0,1.0,202.00,100.33,202.0,100.33,0.0,N,3.0,2.0,2250000.0,27166050.0,2250000.0,27166050.0,1927.0,1998.0,2000.0,17.57,2.43,0.0,4.8,3.0,3.002300e+09,0.0,301.0,985622.0,193713.0,12d,302 014,30106.0,0.000000e+00,1.0,17V1.1,0.0,620.761169,21360.147631

In [9]:
#сохранение данных в файл, чтобы в случае чего не приходилось считать по несколько раз одно и то же.
bsm_data.to_csv('bsm_data1.csv')

In [10]:
bsm_1 = pd.read_csv('bsm_data1.csv')

In [68]:
#Удаление всех строк с Nan больше 40%
delet2=[]
for i in range(bsm_1.shape[0]):
    temp = 0
    for j in range(bsm_1.shape[1]):
        if (pd.isna(bsm_1[bsm_1.columns[j]][i])):
            temp += 1
    if(temp >= bsm_1.shape[1]*0.4):
        delet2.append(i)
bsm_1 = bsm_1.drop(labels= delet2,axis = 0)
bsm_1.shape

(303728, 91)

In [ ]:
bsm_1 = bsm_1.drop(['Unnamed: 0',], axis=1)

In [189]:
bsm_1.head()

,borough,neighborhood,building_class_category,tax_class,block,lot,building_class,address,zip_code,residential_units,commercial_units,total_units,land_sqft,gross_sqft,year_built,tax_class_at_sale,building_class_at_sale,sale_price,sale_date,year_of_sale,Borough,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,PolicePrct,HealthCent,HealthArea,SanitBoro,SanitDistr,SanitSub,Address,ZoneDist1,SplitZone,BldgClass,LandUse,Easements,OwnerName,LotArea,BldgArea,ComArea,ResArea,OfficeArea,RetailArea,GarageArea,StrgeArea,FactryArea,OtherArea,AreaSource,NumBldgs,NumFloors,UnitsRes,UnitsTotal,LotFront,LotDepth,BldgFront,BldgDepth,ProxCode,IrrLotCode,LotType,BsmtCode,AssessLand,AssessTot,ExemptLand,ExemptTot,YearBuilt,YearAlter1,YearAlter2,BuiltFAR,ResidFAR,CommFAR,FacilFAR,BoroCode,BBL,CondoNo,Tract2010,XCoord,YCoord,ZoneMap,Sanborn,TaxMap,APPBBL,PLUTOMapID,Version,MAPPLUTO_F,SHAPE_Leng,SHAPE_Area
1,3,DOWNTOWN-FULTON FERRY,29 COMMERCIAL GARAGES,4,54,1,G7,85 JAY STREET,11201,0,0,0,134988.0,0.0,0,4,G7,345000000.0,2016-12-20,2016,BK,302.0,21.00,3017.0,13.0,33.0,11201.0,L118,84.0,36.0,1000.0,3.0,2.0,1B,87 JAY STREET,M1-2/R8,N,G7,10.0,0.0,85 JAY STREET BROOKLY,134988.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,490.50,275.33,0.0,0.00,0.0,N,5.0,5.0,1571850.0,1571850.0,1571850.0,1571850.0,0.0,0.0,0.0,0.00,7.20,2.0,6.5,3.0,3.000540e+09,0.0,21.0,988208.0,195011.0,12d,302 016,30101.0,3.000540e+09,1.0,17V1.1,0.0,1559.889144,140131.577176
2,3,BROOKLYN HEIGHTS,21 OFFICE BUILDINGS,4,204,1,O6,29 COLUMBIA HEIGHTS,11201,0,0,0,32000.0,304650.0,1924,4,O6,340000000.0,2016-08-03,2016,BK,302.0,1.00,1003.0,13.0,33.0,11201.0,E205,84.0,38.0,2300.0,3.0,2.0,1A,29 COLUMBIA HEIGHTS,M2-1,N,O6,5.0,0.0,25-30 COLUMBIA HEIGHT,32000.0,304650.0,304650.0,0.0,264750.0,0.0,0.0,0.0,0.0,39900.0,2.0,1.0,13.0,0.0,0.0,92.42,335.92,335.0,92.00,0.0,Y,3.0,5.0,1548000.0,25463250.0,0.0,0.0,1924.0,1980.0,0.0,9.52,0.00,2.0,0.0,3.0,3.002040e+09,0.0,1.0,985952.0,195007.0,12d,302 004,30106.0,0.000000e+00,1.0,17V1.1,0.0,890.718521,34656.447240
3,3,MILL BASIN,22 STORE BUILDINGS,4,8470,55,K6,5120 AVENUE U,11234,0,123,123,905000.0,2548000.0,1970,4,K6,276947000.0,2012-11-28,2012,BK,318.0,698.00,2005.0,22.0,46.0,11234.0,E323,63.0,35.0,8822.0,3.0,18.0,4E,5120 AVENUE U,M3-1,N,K6,5.0,1.0,BROOKLYN KINGS PLAZA,905000.0,2548000.0,2548000.0,0.0,0.0,1263000.0,1285000.0,0.0,0.0,0.0,2.0,4.0,2.0,0.0,123.0,930.00,859.00,0.0,0.00,0.0,Y,3.0,5.0,36532350.0,149792400.0,0.0,0.0,1970.0,0.0,0.0,2.82,0.00,2.0,0.0,3.0,3.084700e+09,0.0,698.0,1006597.0,161424.0,23b,319 077,32502.0,0.000000e+00,1.0,17V1.1,0.0,3729.786857,797554.847834
4,3,BROOKLYN HEIGHTS,26 OTHER HOTELS,4,230,1,H8,21 CLARK STREET,11201,0,1,1,20267.0,356000.0,1927,4,H8,202500000.0,2017-10-31,2017,BK,302.0,3.01,2000.0,13.0,33.0,11201.0,E205,84.0,38.0,2300.0,3.0,2.0,1A,79 WILLOW STREET,R6,N,H8,8.0,0.0,WATCHTOWER C/O REAL P,20267.0,356000.0,30000.0,0.0,30000.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,15.0,0.0,1.0,202.00,100.33,202.0,100.33,0.0,N,3.0,2.0,2250000.0,27166050.0,2250000.0,27166050.0,1927.0,1998.0,2000.0,17.57,2.43,0.0,4.8,3.0,3.002300e+09,0.0,301.0,985622.0,193713.0,12d,302 014,30106.0,0.000000e+00,1.0,17V1.1,0.0,620.761169,21360.147631
5,3,WILLIAMSBURG-SOUTH,31 COMMERCIAL VACANT LAND,4,2428,1,V1,329 KENT AVENUE,11249,0,0,0,57600.0,0.0,0,4,V1,185445000.0,2012-10-11,2012,BK,301.0,551.00,1009.0,14.0,33.0,11249.0,E221,90.0,30.0,400.0,3.0,1.0,2B,325 KENT AVENUE,R6,N,D7,4.0,0.0,325 KENT LLC,57600.0,382746.0,11200.0,371546.0,1822.0,9378.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,522.0,525.0,180.00,320.00,179.0,315.00,0.0,N,3.0,5.0,3110400.0,5579990.0,0.0,0.0,2015.0,0.0,0.0,6.64,2.43,0.0,4.8,3.0,3.024280e+09,0.0,551.0,993500.0,199202.0,12d,303 007,30806.0,0.000000e+00,1.0,17V1.1,0.0,1006.337999,58564.864312

In [194]:
#сохранение данных в файл, чтобы в случае чего не приходилось считать по несколько раз одно и то же.
bsm_1.to_csv('bsm_data2.csv')

In [15]:
bsm_2 = pd.read_csv('bsm_data2.csv')

In [16]:
bsm_2 = bsm_2.drop(['Unnamed: 0',], axis=1)

In [17]:
#удаление строк с nan в целевых переменных
bsm_2 = bsm_2[pd.isna(bsm_2["building_class_category"]) == False]
bsm_2 = bsm_2[pd.isna(bsm_2["sale_price"]) == False]
bsm_2.head()

,borough,neighborhood,building_class_category,tax_class,block,lot,building_class,address,zip_code,residential_units,commercial_units,total_units,land_sqft,gross_sqft,year_built,tax_class_at_sale,building_class_at_sale,sale_price,sale_date,year_of_sale,Borough,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,PolicePrct,HealthCent,HealthArea,SanitBoro,SanitDistr,SanitSub,Address,ZoneDist1,SplitZone,BldgClass,LandUse,Easements,OwnerName,LotArea,BldgArea,ComArea,ResArea,OfficeArea,RetailArea,GarageArea,StrgeArea,FactryArea,OtherArea,AreaSource,NumBldgs,NumFloors,UnitsRes,UnitsTotal,LotFront,LotDepth,BldgFront,BldgDepth,ProxCode,IrrLotCode,LotType,BsmtCode,AssessLand,AssessTot,ExemptLand,ExemptTot,YearBuilt,YearAlter1,YearAlter2,BuiltFAR,ResidFAR,CommFAR,FacilFAR,BoroCode,BBL,CondoNo,Tract2010,XCoord,YCoord,ZoneMap,Sanborn,TaxMap,APPBBL,PLUTOMapID,Version,MAPPLUTO_F,SHAPE_Leng,SHAPE_Area
0,3,DOWNTOWN-FULTON FERRY,29 COMMERCIAL GARAGES,4,54,1,G7,85 JAY STREET,11201,0,0,0,134988.0,0.0,0,4,G7,345000000.0,2016-12-20,2016,BK,302.0,21.00,3017.0,13.0,33.0,11201.0,L118,84.0,36.0,1000.0,3.0,2.0,1B,87 JAY STREET,M1-2/R8,N,G7,10.0,0.0,85 JAY STREET BROOKLY,134988.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,490.50,275.33,0.0,0.00,0.0,N,5.0,5.0,1571850.0,1571850.0,1571850.0,1571850.0,0.0,0.0,0.0,0.00,7.20,2.0,6.5,3.0,3.000540e+09,0.0,21.0,988208.0,195011.0,12d,302 016,30101.0,3.000540e+09,1.0,17V1.1,0.0,1559.889144,140131.577176
1,3,BROOKLYN HEIGHTS,21 OFFICE BUILDINGS,4,204,1,O6,29 COLUMBIA HEIGHTS,11201,0,0,0,32000.0,304650.0,1924,4,O6,340000000.0,2016-08-03,2016,BK,302.0,1.00,1003.0,13.0,33.0,11201.0,E205,84.0,38.0,2300.0,3.0,2.0,1A,29 COLUMBIA HEIGHTS,M2-1,N,O6,5.0,0.0,25-30 COLUMBIA HEIGHT,32000.0,304650.0,304650.0,0.0,264750.0,0.0,0.0,0.0,0.0,39900.0,2.0,1.0,13.0,0.0,0.0,92.42,335.92,335.0,92.00,0.0,Y,3.0,5.0,1548000.0,25463250.0,0.0,0.0,1924.0,1980.0,0.0,9.52,0.00,2.0,0.0,3.0,3.002040e+09,0.0,1.0,985952.0,195007.0,12d,302 004,30106.0,0.000000e+00,1.0,17V1.1,0.0,890.718521,34656.447240
2,3,MILL BASIN,22 STORE BUILDINGS,4,8470,55,K6,5120 AVENUE U,11234,0,123,123,905000.0,2548000.0,1970,4,K6,276947000.0,2012-11-28,2012,BK,318.0,698.00,2005.0,22.0,46.0,11234.0,E323,63.0,35.0,8822.0,3.0,18.0,4E,5120 AVENUE U,M3-1,N,K6,5.0,1.0,BROOKLYN KINGS PLAZA,905000.0,2548000.0,2548000.0,0.0,0.0,1263000.0,1285000.0,0.0,0.0,0.0,2.0,4.0,2.0,0.0,123.0,930.00,859.00,0.0,0.00,0.0,Y,3.0,5.0,36532350.0,149792400.0,0.0,0.0,1970.0,0.0,0.0,2.82,0.00,2.0,0.0,3.0,3.084700e+09,0.0,698.0,1006597.0,161424.0,23b,319 077,32502.0,0.000000e+00,1.0,17V1.1,0.0,3729.786857,797554.847834
3,3,BROOKLYN HEIGHTS,26 OTHER HOTELS,4,230,1,H8,21 CLARK STREET,11201,0,1,1,20267.0,356000.0,1927,4,H8,202500000.0,2017-10-31,2017,BK,302.0,3.01,2000.0,13.0,33.0,11201.0,E205,84.0,38.0,2300.0,3.0,2.0,1A,79 WILLOW STREET,R6,N,H8,8.0,0.0,WATCHTOWER C/O REAL P,20267.0,356000.0,30000.0,0.0,30000.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,15.0,0.0,1.0,202.00,100.33,202.0,100.33,0.0,N,3.0,2.0,2250000.0,27166050.0,2250000.0,27166050.0,1927.0,1998.0,2000.0,17.57,2.43,0.0,4.8,3.0,3.002300e+09,0.0,301.0,985622.0,193713.0,12d,302 014,30106.0,0.000000e+00,1.0,17V1.1,0.0,620.761169,21360.147631
4,3,WILLIAMSBURG-SOUTH,31 COMMERCIAL VACANT LAND,4,2428,1,V1,329 KENT AVENUE,11249,0,0,0,57600.0,0.0,0,4,V1,185445000.0,2012-10-11,2012,BK,301.0,551.00,1009.0,14.0,33.0,11249.0,E221,90.0,30.0,400.0,3.0,1.0,2B,325 KENT AVENUE,R6,N,D7,4.0,0.0,325 KENT LLC,57600.0,382746.0,11200.0,371546.0,1822.0,9378.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,522.0,525.0,180.00,320.00,179.0,315.00,0.0,N,3.0,5.0,3110400.0,5579990.0,0.0,0.0,2015.0,0.0,0.0,6.64,2.43,0.0,4.8,3.0,3.024280e+09,0.0,551.0,993500.0,199202.0,12d,303 007,30806.0,0.000000e+00,1.0,17V1.1,0.0,1006.337999,58564.864312

In [18]:
#Окончательное збавление от Nan
for namecol in bsm_2.columns:
    if(bsm_2[namecol].dtype == np.float64 or bsm_2[namecol].dtype == np.int64):
        bsm_2 = bsm_2.fillna(value = {namecol: bsm_2[namecol].median()})

bsm_2 = bsm_2.fillna(method = 'ffill')
bsm_2.head()

,borough,neighborhood,building_class_category,tax_class,block,lot,building_class,address,zip_code,residential_units,commercial_units,total_units,land_sqft,gross_sqft,year_built,tax_class_at_sale,building_class_at_sale,sale_price,sale_date,year_of_sale,Borough,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,PolicePrct,HealthCent,HealthArea,SanitBoro,SanitDistr,SanitSub,Address,ZoneDist1,SplitZone,BldgClass,LandUse,Easements,OwnerName,LotArea,BldgArea,ComArea,ResArea,OfficeArea,RetailArea,GarageArea,StrgeArea,FactryArea,OtherArea,AreaSource,NumBldgs,NumFloors,UnitsRes,UnitsTotal,LotFront,LotDepth,BldgFront,BldgDepth,ProxCode,IrrLotCode,LotType,BsmtCode,AssessLand,AssessTot,ExemptLand,ExemptTot,YearBuilt,YearAlter1,YearAlter2,BuiltFAR,ResidFAR,CommFAR,FacilFAR,BoroCode,BBL,CondoNo,Tract2010,XCoord,YCoord,ZoneMap,Sanborn,TaxMap,APPBBL,PLUTOMapID,Version,MAPPLUTO_F,SHAPE_Leng,SHAPE_Area
0,3,DOWNTOWN-FULTON FERRY,29 COMMERCIAL GARAGES,4,54,1,G7,85 JAY STREET,11201,0,0,0,134988.0,0.0,0,4,G7,345000000.0,2016-12-20,2016,BK,302.0,21.00,3017.0,13.0,33.0,11201.0,L118,84.0,36.0,1000.0,3.0,2.0,1B,87 JAY STREET,M1-2/R8,N,G7,10.0,0.0,85 JAY STREET BROOKLY,134988.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,490.50,275.33,0.0,0.00,0.0,N,5.0,5.0,1571850.0,1571850.0,1571850.0,1571850.0,0.0,0.0,0.0,0.00,7.20,2.0,6.5,3.0,3.000540e+09,0.0,21.0,988208.0,195011.0,12d,302 016,30101.0,3.000540e+09,1.0,17V1.1,0.0,1559.889144,140131.577176
1,3,BROOKLYN HEIGHTS,21 OFFICE BUILDINGS,4,204,1,O6,29 COLUMBIA HEIGHTS,11201,0,0,0,32000.0,304650.0,1924,4,O6,340000000.0,2016-08-03,2016,BK,302.0,1.00,1003.0,13.0,33.0,11201.0,E205,84.0,38.0,2300.0,3.0,2.0,1A,29 COLUMBIA HEIGHTS,M2-1,N,O6,5.0,0.0,25-30 COLUMBIA HEIGHT,32000.0,304650.0,304650.0,0.0,264750.0,0.0,0.0,0.0,0.0,39900.0,2.0,1.0,13.0,0.0,0.0,92.42,335.92,335.0,92.00,0.0,Y,3.0,5.0,1548000.0,25463250.0,0.0,0.0,1924.0,1980.0,0.0,9.52,0.00,2.0,0.0,3.0,3.002040e+09,0.0,1.0,985952.0,195007.0,12d,302 004,30106.0,0.000000e+00,1.0,17V1.1,0.0,890.718521,34656.447240
2,3,MILL BASIN,22 STORE BUILDINGS,4,8470,55,K6,5120 AVENUE U,11234,0,123,123,905000.0,2548000.0,1970,4,K6,276947000.0,2012-11-28,2012,BK,318.0,698.00,2005.0,22.0,46.0,11234.0,E323,63.0,35.0,8822.0,3.0,18.0,4E,5120 AVENUE U,M3-1,N,K6,5.0,1.0,BROOKLYN KINGS PLAZA,905000.0,2548000.0,2548000.0,0.0,0.0,1263000.0,1285000.0,0.0,0.0,0.0,2.0,4.0,2.0,0.0,123.0,930.00,859.00,0.0,0.00,0.0,Y,3.0,5.0,36532350.0,149792400.0,0.0,0.0,1970.0,0.0,0.0,2.82,0.00,2.0,0.0,3.0,3.084700e+09,0.0,698.0,1006597.0,161424.0,23b,319 077,32502.0,0.000000e+00,1.0,17V1.1,0.0,3729.786857,797554.847834
3,3,BROOKLYN HEIGHTS,26 OTHER HOTELS,4,230,1,H8,21 CLARK STREET,11201,0,1,1,20267.0,356000.0,1927,4,H8,202500000.0,2017-10-31,2017,BK,302.0,3.01,2000.0,13.0,33.0,11201.0,E205,84.0,38.0,2300.0,3.0,2.0,1A,79 WILLOW STREET,R6,N,H8,8.0,0.0,WATCHTOWER C/O REAL P,20267.0,356000.0,30000.0,0.0,30000.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,15.0,0.0,1.0,202.00,100.33,202.0,100.33,0.0,N,3.0,2.0,2250000.0,27166050.0,2250000.0,27166050.0,1927.0,1998.0,2000.0,17.57,2.43,0.0,4.8,3.0,3.002300e+09,0.0,301.0,985622.0,193713.0,12d,302 014,30106.0,0.000000e+00,1.0,17V1.1,0.0,620.761169,21360.147631
4,3,WILLIAMSBURG-SOUTH,31 COMMERCIAL VACANT LAND,4,2428,1,V1,329 KENT AVENUE,11249,0,0,0,57600.0,0.0,0,4,V1,185445000.0,2012-10-11,2012,BK,301.0,551.00,1009.0,14.0,33.0,11249.0,E221,90.0,30.0,400.0,3.0,1.0,2B,325 KENT AVENUE,R6,N,D7,4.0,0.0,325 KENT LLC,57600.0,382746.0,11200.0,371546.0,1822.0,9378.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,522.0,525.0,180.00,320.00,179.0,315.00,0.0,N,3.0,5.0,3110400.0,5579990.0,0.0,0.0,2015.0,0.0,0.0,6.64,2.43,0.0,4.8,3.0,3.024280e+09,0.0,551.0,993500.0,199202.0,12d,303 007,30806.0,0.000000e+00,1.0,17V1.1,0.0,1006.337999,58564.864312

In [19]:
#Удаление столбца Address, так как аналогичный уже есть.
bsm_2 = bsm_2.drop(['Address',], axis=1)

In [20]:
#Столбец имён достаточно бесполезен.
bsm_2 = bsm_2.drop(['OwnerName',], axis=1)

In [21]:
#Столбцы одного и того же значения.
bsm_2 = bsm_2.drop(['borough',], axis=1)
bsm_2 = bsm_2.drop(['Borough',], axis=1)
bsm_2 = bsm_2.drop(['PLUTOMapID',], axis=1)

In [22]:
#Проверка на столбцы одного и того же значения.
names_3 = bsm_2.columns
deletee_3 = []

for i in range(bsm_2.shape[1]):
    if(bsm_2.nunique()[i] == 1):
        deletee_3.append(names_3[i])

bsm_2 = bsm_2.drop(deletee_3, axis=1)
bsm_2.shape[1]

83

In [24]:
#проверка на существование nan
n = 0
for i in range(50000):
    temp = 0
    for j in range(bsm_2.shape[1]):
        if (pd.isna(bsm_2[bsm_2.columns[j]][i])):
            temp += 1
    if(temp > 0):
        print('есть nan в строке',i)
        n+=1
    if i%5000 == 0:
        print('Проверено',i,'строк.')
if n==0:
    print('nan не найдены!')

Проверено 0 строк.
Проверено 5000 строк.
Проверено 10000 строк.
Проверено 15000 строк.
Проверено 20000 строк.
Проверено 25000 строк.
Проверено 30000 строк.
Проверено 35000 строк.
Проверено 40000 строк.
Проверено 45000 строк.
nan не найдены!

In [203]:
# Изначально хотелось бы перевести все адреса в улицы, вышел бы достаточно хороший и полезный столбец, 
# однако мощностей ноутбука просто не хватает на такое.

#bsm_2["address"]= bsm_2["address"].fillna(method= "ffill")

#for i in range(bsm_2.shape[0]): 
#    bsm_2["address"][i] = " ".join(bsm_2["address"][i].split()[1:])
#    if i%50000 == 0:
#        print('Проверено',i,'строк.')

In [25]:
#Так как мои мощности не позволяют воспользоваться столбцом address, придётся его просто удалить.
bsm_2 = bsm_2.drop(['address',], axis=1)

In [28]:
bsm_2.head()

,neighborhood,building_class_category,tax_class,block,lot,building_class,zip_code,residential_units,commercial_units,total_units,land_sqft,gross_sqft,year_built,tax_class_at_sale,building_class_at_sale,sale_price,sale_date,year_of_sale,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,PolicePrct,HealthCent,HealthArea,SanitBoro,SanitDistr,SanitSub,ZoneDist1,SplitZone,BldgClass,LandUse,Easements,LotArea,BldgArea,ComArea,ResArea,OfficeArea,RetailArea,GarageArea,StrgeArea,FactryArea,OtherArea,AreaSource,NumBldgs,NumFloors,UnitsRes,UnitsTotal,LotFront,LotDepth,BldgFront,BldgDepth,ProxCode,IrrLotCode,LotType,BsmtCode,AssessLand,AssessTot,ExemptLand,ExemptTot,YearBuilt,YearAlter1,YearAlter2,BuiltFAR,ResidFAR,CommFAR,FacilFAR,BBL,CondoNo,Tract2010,XCoord,YCoord,ZoneMap,Sanborn,TaxMap,APPBBL,MAPPLUTO_F,SHAPE_Leng,SHAPE_Area
0,DOWNTOWN-FULTON FERRY,29 COMMERCIAL GARAGES,4,54,1,G7,11201,0,0,0,134988.0,0.0,0,4,G7,345000000.0,2016-12-20,2016,302.0,21.00,3017.0,13.0,33.0,11201.0,L118,84.0,36.0,1000.0,3.0,2.0,1B,M1-2/R8,N,G7,10.0,0.0,134988.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,490.50,275.33,0.0,0.00,0.0,N,5.0,5.0,1571850.0,1571850.0,1571850.0,1571850.0,0.0,0.0,0.0,0.00,7.20,2.0,6.5,3.000540e+09,0.0,21.0,988208.0,195011.0,12d,302 016,30101.0,3.000540e+09,0.0,1559.889144,140131.577176
1,BROOKLYN HEIGHTS,21 OFFICE BUILDINGS,4,204,1,O6,11201,0,0,0,32000.0,304650.0,1924,4,O6,340000000.0,2016-08-03,2016,302.0,1.00,1003.0,13.0,33.0,11201.0,E205,84.0,38.0,2300.0,3.0,2.0,1A,M2-1,N,O6,5.0,0.0,32000.0,304650.0,304650.0,0.0,264750.0,0.0,0.0,0.0,0.0,39900.0,2.0,1.0,13.0,0.0,0.0,92.42,335.92,335.0,92.00,0.0,Y,3.0,5.0,1548000.0,25463250.0,0.0,0.0,1924.0,1980.0,0.0,9.52,0.00,2.0,0.0,3.002040e+09,0.0,1.0,985952.0,195007.0,12d,302 004,30106.0,0.000000e+00,0.0,890.718521,34656.447240
2,MILL BASIN,22 STORE BUILDINGS,4,8470,55,K6,11234,0,123,123,905000.0,2548000.0,1970,4,K6,276947000.0,2012-11-28,2012,318.0,698.00,2005.0,22.0,46.0,11234.0,E323,63.0,35.0,8822.0,3.0,18.0,4E,M3-1,N,K6,5.0,1.0,905000.0,2548000.0,2548000.0,0.0,0.0,1263000.0,1285000.0,0.0,0.0,0.0,2.0,4.0,2.0,0.0,123.0,930.00,859.00,0.0,0.00,0.0,Y,3.0,5.0,36532350.0,149792400.0,0.0,0.0,1970.0,0.0,0.0,2.82,0.00,2.0,0.0,3.084700e+09,0.0,698.0,1006597.0,161424.0,23b,319 077,32502.0,0.000000e+00,0.0,3729.786857,797554.847834
3,BROOKLYN HEIGHTS,26 OTHER HOTELS,4,230,1,H8,11201,0,1,1,20267.0,356000.0,1927,4,H8,202500000.0,2017-10-31,2017,302.0,3.01,2000.0,13.0,33.0,11201.0,E205,84.0,38.0,2300.0,3.0,2.0,1A,R6,N,H8,8.0,0.0,20267.0,356000.0,30000.0,0.0,30000.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,15.0,0.0,1.0,202.00,100.33,202.0,100.33,0.0,N,3.0,2.0,2250000.0,27166050.0,2250000.0,27166050.0,1927.0,1998.0,2000.0,17.57,2.43,0.0,4.8,3.002300e+09,0.0,301.0,985622.0,193713.0,12d,302 014,30106.0,0.000000e+00,0.0,620.761169,21360.147631
4,WILLIAMSBURG-SOUTH,31 COMMERCIAL VACANT LAND,4,2428,1,V1,11249,0,0,0,57600.0,0.0,0,4,V1,185445000.0,2012-10-11,2012,301.0,551.00,1009.0,14.0,33.0,11249.0,E221,90.0,30.0,400.0,3.0,1.0,2B,R6,N,D7,4.0,0.0,57600.0,382746.0,11200.0,371546.0,1822.0,9378.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,522.0,525.0,180.00,320.00,179.0,315.00,0.0,N,3.0,5.0,3110400.0,5579990.0,0.0,0.0,2015.0,0.0,0.0,6.64,2.43,0.0,4.8,3.024280e+09,0.0,551.0,993500.0,199202.0,12d,303 007,30806.0,0.000000e+00,0.0,1006.337999,58564.864312

In [32]:
#сохранение данных в файл, чтобы в случае чего не приходилось считать по несколько раз одно и то же.
bsm_2.to_csv('bsm_data3.csv')

In [33]:
bsm_3 = pd.read_csv('bsm_data3.csv')

In [34]:
#удаление столбцов с уникальными элементами больше 50к и типом категориальных
names_2 = bsm_3.columns
deletee_2 = []
for i in range(bsm_3.shape[1]):
    
    if(bsm_3.nunique()[i] >= 50000) and (bsm_3[bsm_3.columns[i]].dtype == 'O'):
        deletee_2.append(names_2[i])
        
bsm_3 = bsm_3.drop(deletee_2, axis=1)
bsm_3.shape[1]

83

In [35]:
bsm_3 = bsm_3.drop(['Unnamed: 0',], axis=1)

In [37]:
#сохранение данных в файл, чтобы в случае чего не приходилось считать по несколько раз одно и то же.
bsm_3.to_csv('bsm_data4.csv')

## Модуль B. Классификация
### ОТБОР ПРИЗНАКОВ
#### Необходимо определить, какие признаки имеют наибольшее влияние на классификацию объектов по Строительной категории (building_class_category) и оставить только их для обучения. Могут остаться и все исходные признаки. Необходимо обосновать выбор признаков, оставленных для обучения.

In [3]:
bsm_B = pd.read_csv('bsm_data4.csv')

In [4]:
bsm_B = bsm_B.drop(['Unnamed: 0',], axis=1)

In [5]:
#list(bsm_B.columns)
pd.set_option('display.max_columns', None)
bsm_B.head()

,neighborhood,building_class_category,tax_class,block,lot,building_class,zip_code,residential_units,commercial_units,total_units,land_sqft,gross_sqft,year_built,tax_class_at_sale,building_class_at_sale,sale_price,sale_date,year_of_sale,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,PolicePrct,HealthCent,HealthArea,SanitBoro,SanitDistr,SanitSub,ZoneDist1,SplitZone,BldgClass,LandUse,Easements,LotArea,BldgArea,ComArea,ResArea,OfficeArea,RetailArea,GarageArea,StrgeArea,FactryArea,OtherArea,AreaSource,NumBldgs,NumFloors,UnitsRes,UnitsTotal,LotFront,LotDepth,BldgFront,BldgDepth,ProxCode,IrrLotCode,LotType,BsmtCode,AssessLand,AssessTot,ExemptLand,ExemptTot,YearBuilt,YearAlter1,YearAlter2,BuiltFAR,ResidFAR,CommFAR,FacilFAR,BBL,CondoNo,Tract2010,XCoord,YCoord,ZoneMap,Sanborn,TaxMap,APPBBL,MAPPLUTO_F,SHAPE_Leng,SHAPE_Area
0,DOWNTOWN-FULTON FERRY,29 COMMERCIAL GARAGES,4,54,1,G7,11201,0,0,0,134988.0,0.0,0,4,G7,345000000.0,2016-12-20,2016,302.0,21.00,3017.0,13.0,33.0,11201.0,L118,84.0,36.0,1000.0,3.0,2.0,1B,M1-2/R8,N,G7,10.0,0.0,134988.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,490.50,275.33,0.0,0.00,0.0,N,5.0,5.0,1571850.0,1571850.0,1571850.0,1571850.0,0.0,0.0,0.0,0.00,7.20,2.0,6.5,3.000540e+09,0.0,21.0,988208.0,195011.0,12d,302 016,30101.0,3.000540e+09,0.0,1559.889144,140131.577176
1,BROOKLYN HEIGHTS,21 OFFICE BUILDINGS,4,204,1,O6,11201,0,0,0,32000.0,304650.0,1924,4,O6,340000000.0,2016-08-03,2016,302.0,1.00,1003.0,13.0,33.0,11201.0,E205,84.0,38.0,2300.0,3.0,2.0,1A,M2-1,N,O6,5.0,0.0,32000.0,304650.0,304650.0,0.0,264750.0,0.0,0.0,0.0,0.0,39900.0,2.0,1.0,13.0,0.0,0.0,92.42,335.92,335.0,92.00,0.0,Y,3.0,5.0,1548000.0,25463250.0,0.0,0.0,1924.0,1980.0,0.0,9.52,0.00,2.0,0.0,3.002040e+09,0.0,1.0,985952.0,195007.0,12d,302 004,30106.0,0.000000e+00,0.0,890.718521,34656.447240
2,MILL BASIN,22 STORE BUILDINGS,4,8470,55,K6,11234,0,123,123,905000.0,2548000.0,1970,4,K6,276947000.0,2012-11-28,2012,318.0,698.00,2005.0,22.0,46.0,11234.0,E323,63.0,35.0,8822.0,3.0,18.0,4E,M3-1,N,K6,5.0,1.0,905000.0,2548000.0,2548000.0,0.0,0.0,1263000.0,1285000.0,0.0,0.0,0.0,2.0,4.0,2.0,0.0,123.0,930.00,859.00,0.0,0.00,0.0,Y,3.0,5.0,36532350.0,149792400.0,0.0,0.0,1970.0,0.0,0.0,2.82,0.00,2.0,0.0,3.084700e+09,0.0,698.0,1006597.0,161424.0,23b,319 077,32502.0,0.000000e+00,0.0,3729.786857,797554.847834
3,BROOKLYN HEIGHTS,26 OTHER HOTELS,4,230,1,H8,11201,0,1,1,20267.0,356000.0,1927,4,H8,202500000.0,2017-10-31,2017,302.0,3.01,2000.0,13.0,33.0,11201.0,E205,84.0,38.0,2300.0,3.0,2.0,1A,R6,N,H8,8.0,0.0,20267.0,356000.0,30000.0,0.0,30000.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,15.0,0.0,1.0,202.00,100.33,202.0,100.33,0.0,N,3.0,2.0,2250000.0,27166050.0,2250000.0,27166050.0,1927.0,1998.0,2000.0,17.57,2.43,0.0,4.8,3.002300e+09,0.0,301.0,985622.0,193713.0,12d,302 014,30106.0,0.000000e+00,0.0,620.761169,21360.147631
4,WILLIAMSBURG-SOUTH,31 COMMERCIAL VACANT LAND,4,2428,1,V1,11249,0,0,0,57600.0,0.0,0,4,V1,185445000.0,2012-10-11,2012,301.0,551.00,1009.0,14.0,33.0,11249.0,E221,90.0,30.0,400.0,3.0,1.0,2B,R6,N,D7,4.0,0.0,57600.0,382746.0,11200.0,371546.0,1822.0,9378.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,522.0,525.0,180.00,320.00,179.0,315.00,0.0,N,3.0,5.0,3110400.0,5579990.0,0.0,0.0,2015.0,0.0,0.0,6.64,2.43,0.0,4.8,3.024280e+09,0.0,551.0,993500.0,199202.0,12d,303 007,30806.0,0.000000e+00,0.0,1006.337999,58564.864312

In [6]:
label = LabelEncoder()
for k in range(bsm_B.shape[1]):
    if(bsm_B[bsm_B.columns[k]].dtype == 'O'):
        bsm_B[bsm_B.columns[k]]=label.fit_transform(bsm_B[bsm_B.columns[k]])
bsm_B.head()

,neighborhood,building_class_category,tax_class,block,lot,building_class,zip_code,residential_units,commercial_units,total_units,land_sqft,gross_sqft,year_built,tax_class_at_sale,building_class_at_sale,sale_price,sale_date,year_of_sale,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,PolicePrct,HealthCent,HealthArea,SanitBoro,SanitDistr,SanitSub,ZoneDist1,SplitZone,BldgClass,LandUse,Easements,LotArea,BldgArea,ComArea,ResArea,OfficeArea,RetailArea,GarageArea,StrgeArea,FactryArea,OtherArea,AreaSource,NumBldgs,NumFloors,UnitsRes,UnitsTotal,LotFront,LotDepth,BldgFront,BldgDepth,ProxCode,IrrLotCode,LotType,BsmtCode,AssessLand,AssessTot,ExemptLand,ExemptTot,YearBuilt,YearAlter1,YearAlter2,BuiltFAR,ResidFAR,CommFAR,FacilFAR,BBL,CondoNo,Tract2010,XCoord,YCoord,ZoneMap,Sanborn,TaxMap,APPBBL,MAPPLUTO_F,SHAPE_Leng,SHAPE_Area
0,21,34,8,54,1,52,11201,0,0,0,134988.0,0.0,0,4,52,345000000.0,4982,2016,302.0,21.00,3017.0,13.0,33.0,11201.0,75,84.0,36.0,1000.0,3.0,2.0,1,33,0,50,10.0,0.0,134988.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,490.50,275.33,0.0,0.00,0.0,0,5.0,5.0,1571850.0,1571850.0,1571850.0,1571850.0,0.0,0.0,0.0,0.00,7.20,2.0,6.5,3.000540e+09,0.0,21.0,988208.0,195011.0,1,73,30101.0,3.000540e+09,0.0,1559.889144,140131.577176
1,8,23,8,204,1,104,11201,0,0,0,32000.0,304650.0,1924,4,105,340000000.0,4850,2016,302.0,1.00,1003.0,13.0,33.0,11201.0,2,84.0,38.0,2300.0,3.0,2.0,0,45,0,106,5.0,0.0,32000.0,304650.0,304650.0,0.0,264750.0,0.0,0.0,0.0,0.0,39900.0,2.0,1.0,13.0,0.0,0.0,92.42,335.92,335.0,92.00,0.0,1,3.0,5.0,1548000.0,25463250.0,0.0,0.0,1924.0,1980.0,0.0,9.52,0.00,2.0,0.0,3.002040e+09,0.0,1.0,985952.0,195007.0,1,61,30106.0,0.000000e+00,0.0,890.718521,34656.447240
2,42,25,8,8470,55,81,11234,0,123,123,905000.0,2548000.0,1970,4,82,276947000.0,3544,2012,318.0,698.00,2005.0,22.0,46.0,11234.0,58,63.0,35.0,8822.0,3.0,18.0,21,46,0,83,5.0,1.0,905000.0,2548000.0,2548000.0,0.0,0.0,1263000.0,1285000.0,0.0,0.0,0.0,2.0,4.0,2.0,0.0,123.0,930.00,859.00,0.0,0.00,0.0,1,3.0,5.0,36532350.0,149792400.0,0.0,0.0,1970.0,0.0,0.0,2.82,0.00,2.0,0.0,3.084700e+09,0.0,698.0,1006597.0,161424.0,20,1518,32502.0,0.000000e+00,0.0,3729.786857,797554.847834
3,8,31,8,230,1,62,11201,0,1,1,20267.0,356000.0,1927,4,61,202500000.0,5288,2017,302.0,3.01,2000.0,13.0,33.0,11201.0,2,84.0,38.0,2300.0,3.0,2.0,0,64,0,59,8.0,0.0,20267.0,356000.0,30000.0,0.0,30000.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,15.0,0.0,1.0,202.00,100.33,202.0,100.33,0.0,0,3.0,2.0,2250000.0,27166050.0,2250000.0,27166050.0,1927.0,1998.0,2000.0,17.57,2.43,0.0,4.8,3.002300e+09,0.0,301.0,985622.0,193713.0,1,71,30106.0,0.000000e+00,0.0,620.761169,21360.147631
4,59,38,8,2428,1,141,11249,0,0,0,57600.0,0.0,0,4,145,185445000.0,3498,2012,301.0,551.00,1009.0,14.0,33.0,11249.0,13,90.0,30.0,400.0,3.0,1.0,6,64,0,30,4.0,0.0,57600.0,382746.0,11200.0,371546.0,1822.0,9378.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,522.0,525.0,180.00,320.00,179.0,315.00,0.0,0,3.0,5.0,3110400.0,5579990.0,0.0,0.0,2015.0,0.0,0.0,6.64,2.43,0.0,4.8,3.024280e+09,0.0,551.0,993500.0,199202.0,1,125,30806.0,0.000000e+00,0.0,1006.337999,58564.864312

Проведём отбор признаков, оказывающих наибольшее влияние.

In [7]:
bsm_B_test = bsm_B.drop("building_class_category", axis = 1)

x = bsm_B_test.copy() # копируем наш датафрейм в переменную х
y = bsm_B['building_class_category'] # создаем y - целевую переменную

from sklearn.model_selection import train_test_split # подгружаем функцию, которая разбивает данные случ. образом

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33)#, random_state = 1)
# разбиение данных на обучающую и проверочную выборки

y_train

90074     14
207989     0
289557    23
170444     4
248315    14
          ..
131998     1
183192     1
15674      8
90378      0
143312     0
Name: building_class_category, Length: 203497, dtype: int32

In [8]:
from sklearn.ensemble import RandomForestClassifier

rf_cls = RandomForestClassifier(n_estimators=300)

rf_cls.fit(x_train, y_train)

RandomForestClassifier(n_estimators=300)

In [9]:
#Исследование столбцов на их значимость
pd.set_option('display.max_rows', 20)

coef_rf = pd.DataFrame(rf_cls.feature_importances_, x_train.columns, columns=["coef_rf"]).sort_values(by = "coef_rf", ascending = False)

coef_rf.head(10)

                         coef_rf
building_class_at_sale  0.161785
building_class          0.115327
BldgClass               0.080003
residential_units       0.079062
UnitsRes                0.060096
total_units             0.056072
tax_class_at_sale       0.048259
UnitsTotal              0.046820
LandUse                 0.044689
tax_class               0.037450

In [10]:
#Выделение бесполезных столбцов (влияение меньше 0.01)
names_str = coef_rf.index
delete_str = []

for i in range(names_str.shape[0]):
    if coef_rf['coef_rf'][i] >= 0.01:
        delete_str.append(names_str[i])
        
coef_rf = coef_rf.drop(delete_str, axis=0)
coef_rf.shape[0]

63

In [11]:
#удаление бесполезных столбцов
names_str = coef_rf.index
names_col = bsm_B.columns
delete_col = []

for i in range(bsm_B.shape[1]):
    for j in range(names_str.shape[0]):
        if bsm_B.columns[i] == coef_rf.index[j]:
            delete_col.append(names_col[i])

bsm_B = bsm_B.drop(delete_col, axis=1)
bsm_B.shape[1]

19

In [ ]:
#сохранение данных в файл, чтобы в случае чего не приходилось считать по несколько раз одно и то же.
bsm_B.to_csv('bsm_dataB.csv')

In [6]:
bsm_B = pd.read_csv('bsm_dataB.csv')
bsm_B = bsm_B.drop(['Unnamed: 0',], axis=1)

In [7]:
bsm_B.head()

,building_class_category,tax_class,building_class,residential_units,total_units,land_sqft,gross_sqft,tax_class_at_sale,building_class_at_sale,sale_date,year_of_sale,BldgClass,LandUse,BldgArea,ResArea,NumFloors,UnitsRes,UnitsTotal,AssessTot
0,34,8,52,0,0,134988.0,0.0,4,52,4982,2016,50,10.0,0.0,0.0,0.0,0.0,0.0,1571850.0
1,23,8,104,0,0,32000.0,304650.0,4,105,4850,2016,106,5.0,304650.0,0.0,13.0,0.0,0.0,25463250.0
2,25,8,81,0,123,905000.0,2548000.0,4,82,3544,2012,83,5.0,2548000.0,0.0,2.0,0.0,123.0,149792400.0
3,31,8,62,0,1,20267.0,356000.0,4,61,5288,2017,59,8.0,356000.0,0.0,15.0,0.0,1.0,27166050.0
4,38,8,141,0,0,57600.0,0.0,4,145,3498,2012,30,4.0,382746.0,371546.0,0.0,522.0,525.0,5579990.0

###  РАЗБИЕНИЕ ОБРАБОТАННЫХ ДАННЫХ НА ОБУЧАЮЩУЮ И ТЕСТИРУЮЩУЮ ВЫБОРКИ
#### Необходимо определить принцип разделения данных на обучающую и тестовую выборки. Даже если вы выбираете случайное разделение данных, необходимо обосновать выбор данного принципа.

In [8]:
bsm_B_test = bsm_B.drop("building_class_category", axis = 1)

x = bsm_B_test.copy() # копируем наш датафрейм в переменную х
y = bsm_B['building_class_category'] # создаем y - целевую переменную

from sklearn.model_selection import train_test_split # подгружаем функцию, которая разбивает данные случ. образом

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33)#, random_state = 1)
# разбиение данных на обучающую и проверочную выборки

y_train

184913     2
212515    25
200975     1
159205     1
246427    12
          ..
144205     1
195660    50
202979     2
87437      1
212671     0
Name: building_class_category, Length: 203497, dtype: int64

### КЛАССИФИФКАЦИЯ ОБЪЕКТОВ
#### Необходимо выбрать модель классификации домов по Строительной категории (building_class_category), обосновать выбор модели. Необходимо обучить модель на обучающей выборке и протестировать. Необходимо предоставить показатели точности работы выбранной модели и всех рассматриваемых.

In [9]:
from sklearn.metrics import classification_report # загружаем метрику отчет о классификации
from sklearn.model_selection import GridSearchCV

##### 2.3.1 RandomForestClassifier (алгоритм случайного леса)

In [20]:
from sklearn.ensemble import RandomForestClassifier

rf_cls = RandomForestClassifier(n_estimators=300)

rf_cls.fit(x_train, y_train)

RandomForestClassifier(n_estimators=300)

In [21]:
y_pred = rf_cls.predict(x_test)

print(classification_report(y_test, y_pred)) # проверяем точность с помощью classification report

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     17619
           1       1.00      1.00      1.00     34385
           2       1.00      1.00      1.00     12578
           3       0.50      1.00      0.67         1
           4       0.99      1.00      1.00      1770
           5       1.00      1.00      1.00        88
           6       0.99      0.97      0.98       233
           7       1.00      1.00      1.00        15
           8       1.00      1.00      1.00      9052
           9       1.00      1.00      1.00       478
          10       1.00      0.99      1.00       586
          11       0.97      1.00      0.99        33
          12       1.00      1.00      1.00      2721
          13       1.00      0.99      1.00       190
          14       1.00      1.00      1.00     10339
          15       1.00      1.00      1.00       725
          16       1.00      1.00      1.00         1
          17       0.00      0.00      0.00         1
          18       1.00      1.00      1.00      2123
          19       1.00      0.99      1.00       150
          22       1.00      0.80      0.89         5
          23       0.98      0.98      0.98       366
          24       1.00      1.00      1.00        34
          25       0.99      1.00      0.99      1698
          26       1.00      1.00      1.00       117
          27       0.95      0.70      0.80        50
          28       0.00      0.00      0.00         1
          29       0.75      1.00      0.86         3
          30       0.88      0.78      0.82        18
          31       1.00      1.00      1.00         2
          32       0.99      0.99      0.99       795
          33       1.00      1.00      1.00        26
          34       0.97      0.99      0.98      1385
          35       1.00      1.00      1.00        70
          36       0.99      0.99      0.99       768
          37       1.00      1.00      1.00        39
          38       0.99      1.00      0.99       816
          39       1.00      0.97      0.99        39
          40       0.98      0.93      0.96       107
          41       1.00      1.00      1.00         6
          42       0.99      0.99      0.99        89
          43       1.00      1.00      1.00        13
          44       0.75      0.75      0.75         4
          45       0.00      0.00      0.00         1
          46       0.92      0.89      0.90        62
          47       1.00      1.00      1.00         3
          48       1.00      0.79      0.88        19
          49       1.00      1.00      1.00         1
          50       0.96      0.91      0.94       170
          51       1.00      1.00      1.00         6
          52       0.96      0.88      0.92        26
          53       0.00      0.00      0.00         1
          54       1.00      0.67      0.80         3
          56       1.00      0.50      0.67         2
          57       0.99      0.99      0.99       360
          58       1.00      1.00      1.00        38

    accuracy                           1.00    100231
   macro avg       0.90      0.88      0.89    100231
weighted avg       1.00      1.00      1.00    100231

#####  k-nearest neighbors (KNN) algorithm (алгоритм k-ближайших соседей)

In [22]:
from sklearn.neighbors import KNeighborsClassifier

# создаем объект класс KNeighborsClassifier и задаем начальный гиперпараметр количества соседей
knn_clf = KNeighborsClassifier(n_neighbors=15)

knn_clf.fit(x_train, y_train) # обучаем на тренировочнй выборке

KNeighborsClassifier(n_neighbors=15)

In [23]:
y_pred = knn_clf.predict(x_test) # предсказываем y

print(classification_report(y_test, y_pred)) # проверяем точность с помощью classification report

              precision    recall  f1-score   support

           0       0.70      0.62      0.66     17619
           1       0.67      0.78      0.72     34385
           2       0.58      0.39      0.47     12578
           3       0.00      0.00      0.00         1
           4       0.64      0.51      0.57      1770
           5       0.70      0.24      0.36        88
           6       0.45      0.09      0.14       233
           7       0.50      0.07      0.12        15
           8       0.68      0.85      0.76      9052
           9       0.61      0.09      0.16       478
          10       0.59      0.61      0.60       586
          11       0.00      0.00      0.00        33
          12       0.82      0.96      0.88      2721
          13       0.50      0.01      0.01       190
          14       0.92      0.99      0.95     10339
          15       0.89      0.24      0.38       725
          16       0.00      0.00      0.00         1
          17       0.00      0.00      0.00         1
          18       0.61      0.44      0.51      2123
          19       0.14      0.01      0.01       150
          22       0.00      0.00      0.00         5
          23       0.16      0.08      0.10       366
          24       0.00      0.00      0.00        34
          25       0.43      0.69      0.53      1698
          26       0.14      0.01      0.02       117
          27       1.00      0.02      0.04        50
          28       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         3
          30       0.00      0.00      0.00        18
          31       0.00      0.00      0.00         2
          32       0.35      0.27      0.30       795
          33       0.00      0.00      0.00        26
          34       0.39      0.34      0.36      1385
          35       0.20      0.01      0.03        70
          36       0.37      0.33      0.35       768
          37       0.00      0.00      0.00        39
          38       0.45      0.28      0.35       816
          39       0.00      0.00      0.00        39
          40       0.14      0.01      0.02       107
          41       0.00      0.00      0.00         6
          42       0.30      0.08      0.12        89
          43       0.00      0.00      0.00        13
          44       0.00      0.00      0.00         4
          45       0.00      0.00      0.00         1
          46       0.64      0.11      0.19        62
          47       0.00      0.00      0.00         3
          48       0.00      0.00      0.00        19
          49       0.00      0.00      0.00         1
          50       0.14      0.02      0.04       170
          51       0.00      0.00      0.00         6
          52       1.00      0.04      0.07        26
          53       0.00      0.00      0.00         1
          54       0.00      0.00      0.00         3
          56       0.00      0.00      0.00         2
          57       0.42      0.16      0.24       360
          58       0.50      0.05      0.10        38

    accuracy                           0.68    100231
   macro avg       0.30      0.17      0.18    100231
weighted avg       0.67      0.68      0.66    100231

##### Дерево классификаций

In [10]:
from sklearn.tree import DecisionTreeClassifier # загрузка из sklearn класса дерева классификаций

clf = DecisionTreeClassifier() # создаем объект класса дерева классификаций

clf.fit(x_train, y_train)

DecisionTreeClassifier()

In [11]:
y_pred = clf.predict(x_test)

print(classification_report(y_test, y_pred)) # проверяем точность с помощью classification report

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     17538
           1       1.00      1.00      1.00     34571
           2       1.00      1.00      1.00     12420
           3       1.00      1.00      1.00         1
           4       1.00      1.00      1.00      1849
           5       1.00      1.00      1.00        73
           6       1.00      1.00      1.00       240
           7       1.00      1.00      1.00        15
           8       1.00      1.00      1.00      9095
           9       1.00      1.00      1.00       476
          10       0.99      1.00      0.99       551
          11       0.90      1.00      0.95        26
          12       1.00      1.00      1.00      2635
          13       1.00      1.00      1.00       187
          14       1.00      1.00      1.00     10378
          15       1.00      1.00      1.00       710
          16       0.00      0.00      0.00         3
          17       0.00      0.00      0.00         1
          18       1.00      1.00      1.00      2241
          19       1.00      1.00      1.00       115
          20       0.00      0.00      0.00         0
          21       1.00      0.50      0.67         2
          22       1.00      0.75      0.86         4
          23       1.00      1.00      1.00       363
          24       0.96      1.00      0.98        27
          25       1.00      1.00      1.00      1696
          26       1.00      1.00      1.00       124
          27       1.00      0.95      0.97        40
          28       1.00      1.00      1.00         1
          29       1.00      1.00      1.00         4
          30       1.00      1.00      1.00        20
          31       0.00      0.00      0.00         2
          32       1.00      1.00      1.00       748
          33       1.00      1.00      1.00        26
          34       1.00      1.00      1.00      1319
          35       0.99      1.00      0.99        79
          36       1.00      1.00      1.00       781
          37       1.00      1.00      1.00        49
          38       1.00      1.00      1.00       829
          39       1.00      1.00      1.00        40
          40       1.00      1.00      1.00        96
          41       1.00      1.00      1.00         2
          42       0.99      1.00      1.00       101
          43       0.92      1.00      0.96        12
          44       1.00      1.00      1.00         9
          46       1.00      0.98      0.99        51
          47       1.00      1.00      1.00         3
          48       1.00      1.00      1.00        19
          49       1.00      1.00      1.00         1
          50       1.00      1.00      1.00       189
          51       1.00      1.00      1.00         8
          52       1.00      1.00      1.00        28
          53       1.00      1.00      1.00         1
          54       0.33      0.25      0.29         4
          55       0.00      0.00      0.00         1
          56       1.00      1.00      1.00         2
          57       1.00      1.00      1.00       386
          58       1.00      0.97      0.99        39
          59       0.00      0.00      0.00         0

    accuracy                           1.00    100231
   macro avg       0.88      0.87      0.87    100231
weighted avg       1.00      1.00      1.00    100231

## Модуль C. Восстановление регрессии
### ОТБОР ПРИЗНАКОВ
#### Необходимо определить, какие признаки имеют наибольшее влияние на цены домов (sale_price) и оставить только их для обучения. Могут остаться и все исходные признаки. Необходимо обосновать выбор признаков, оставленных для обучения.

In [71]:
bsm_C = pd.read_csv('bsm_data4.csv')
bsm_C = bsm_C.drop(['Unnamed: 0',], axis=1)

In [72]:
#list(bsm_B.columns)
pd.set_option('display.max_columns', None)
bsm_C.head()

,neighborhood,building_class_category,tax_class,block,lot,building_class,zip_code,residential_units,commercial_units,total_units,land_sqft,gross_sqft,year_built,tax_class_at_sale,building_class_at_sale,sale_price,sale_date,year_of_sale,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,PolicePrct,HealthCent,HealthArea,SanitBoro,SanitDistr,SanitSub,ZoneDist1,SplitZone,BldgClass,LandUse,Easements,LotArea,BldgArea,ComArea,ResArea,OfficeArea,RetailArea,GarageArea,StrgeArea,FactryArea,OtherArea,AreaSource,NumBldgs,NumFloors,UnitsRes,UnitsTotal,LotFront,LotDepth,BldgFront,BldgDepth,ProxCode,IrrLotCode,LotType,BsmtCode,AssessLand,AssessTot,ExemptLand,ExemptTot,YearBuilt,YearAlter1,YearAlter2,BuiltFAR,ResidFAR,CommFAR,FacilFAR,BBL,CondoNo,Tract2010,XCoord,YCoord,ZoneMap,Sanborn,TaxMap,APPBBL,MAPPLUTO_F,SHAPE_Leng,SHAPE_Area
0,DOWNTOWN-FULTON FERRY,29 COMMERCIAL GARAGES,4,54,1,G7,11201,0,0,0,134988.0,0.0,0,4,G7,345000000.0,2016-12-20,2016,302.0,21.00,3017.0,13.0,33.0,11201.0,L118,84.0,36.0,1000.0,3.0,2.0,1B,M1-2/R8,N,G7,10.0,0.0,134988.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,490.50,275.33,0.0,0.00,0.0,N,5.0,5.0,1571850.0,1571850.0,1571850.0,1571850.0,0.0,0.0,0.0,0.00,7.20,2.0,6.5,3.000540e+09,0.0,21.0,988208.0,195011.0,12d,302 016,30101.0,3.000540e+09,0.0,1559.889144,140131.577176
1,BROOKLYN HEIGHTS,21 OFFICE BUILDINGS,4,204,1,O6,11201,0,0,0,32000.0,304650.0,1924,4,O6,340000000.0,2016-08-03,2016,302.0,1.00,1003.0,13.0,33.0,11201.0,E205,84.0,38.0,2300.0,3.0,2.0,1A,M2-1,N,O6,5.0,0.0,32000.0,304650.0,304650.0,0.0,264750.0,0.0,0.0,0.0,0.0,39900.0,2.0,1.0,13.0,0.0,0.0,92.42,335.92,335.0,92.00,0.0,Y,3.0,5.0,1548000.0,25463250.0,0.0,0.0,1924.0,1980.0,0.0,9.52,0.00,2.0,0.0,3.002040e+09,0.0,1.0,985952.0,195007.0,12d,302 004,30106.0,0.000000e+00,0.0,890.718521,34656.447240
2,MILL BASIN,22 STORE BUILDINGS,4,8470,55,K6,11234,0,123,123,905000.0,2548000.0,1970,4,K6,276947000.0,2012-11-28,2012,318.0,698.00,2005.0,22.0,46.0,11234.0,E323,63.0,35.0,8822.0,3.0,18.0,4E,M3-1,N,K6,5.0,1.0,905000.0,2548000.0,2548000.0,0.0,0.0,1263000.0,1285000.0,0.0,0.0,0.0,2.0,4.0,2.0,0.0,123.0,930.00,859.00,0.0,0.00,0.0,Y,3.0,5.0,36532350.0,149792400.0,0.0,0.0,1970.0,0.0,0.0,2.82,0.00,2.0,0.0,3.084700e+09,0.0,698.0,1006597.0,161424.0,23b,319 077,32502.0,0.000000e+00,0.0,3729.786857,797554.847834
3,BROOKLYN HEIGHTS,26 OTHER HOTELS,4,230,1,H8,11201,0,1,1,20267.0,356000.0,1927,4,H8,202500000.0,2017-10-31,2017,302.0,3.01,2000.0,13.0,33.0,11201.0,E205,84.0,38.0,2300.0,3.0,2.0,1A,R6,N,H8,8.0,0.0,20267.0,356000.0,30000.0,0.0,30000.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,15.0,0.0,1.0,202.00,100.33,202.0,100.33,0.0,N,3.0,2.0,2250000.0,27166050.0,2250000.0,27166050.0,1927.0,1998.0,2000.0,17.57,2.43,0.0,4.8,3.002300e+09,0.0,301.0,985622.0,193713.0,12d,302 014,30106.0,0.000000e+00,0.0,620.761169,21360.147631
4,WILLIAMSBURG-SOUTH,31 COMMERCIAL VACANT LAND,4,2428,1,V1,11249,0,0,0,57600.0,0.0,0,4,V1,185445000.0,2012-10-11,2012,301.0,551.00,1009.0,14.0,33.0,11249.0,E221,90.0,30.0,400.0,3.0,1.0,2B,R6,N,D7,4.0,0.0,57600.0,382746.0,11200.0,371546.0,1822.0,9378.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,522.0,525.0,180.00,320.00,179.0,315.00,0.0,N,3.0,5.0,3110400.0,5579990.0,0.0,0.0,2015.0,0.0,0.0,6.64,2.43,0.0,4.8,3.024280e+09,0.0,551.0,993500.0,199202.0,12d,303 007,30806.0,0.000000e+00,0.0,1006.337999,58564.864312

In [73]:
label = LabelEncoder()
for k in range(bsm_C.shape[1]):
    if(bsm_C[bsm_C.columns[k]].dtype == 'O'):
        bsm_C[bsm_C.columns[k]]=label.fit_transform(bsm_C[bsm_C.columns[k]])
bsm_C.head()

,neighborhood,building_class_category,tax_class,block,lot,building_class,zip_code,residential_units,commercial_units,total_units,land_sqft,gross_sqft,year_built,tax_class_at_sale,building_class_at_sale,sale_price,sale_date,year_of_sale,CD,CT2010,CB2010,SchoolDist,Council,ZipCode,FireComp,PolicePrct,HealthCent,HealthArea,SanitBoro,SanitDistr,SanitSub,ZoneDist1,SplitZone,BldgClass,LandUse,Easements,LotArea,BldgArea,ComArea,ResArea,OfficeArea,RetailArea,GarageArea,StrgeArea,FactryArea,OtherArea,AreaSource,NumBldgs,NumFloors,UnitsRes,UnitsTotal,LotFront,LotDepth,BldgFront,BldgDepth,ProxCode,IrrLotCode,LotType,BsmtCode,AssessLand,AssessTot,ExemptLand,ExemptTot,YearBuilt,YearAlter1,YearAlter2,BuiltFAR,ResidFAR,CommFAR,FacilFAR,BBL,CondoNo,Tract2010,XCoord,YCoord,ZoneMap,Sanborn,TaxMap,APPBBL,MAPPLUTO_F,SHAPE_Leng,SHAPE_Area
0,21,34,8,54,1,52,11201,0,0,0,134988.0,0.0,0,4,52,345000000.0,4982,2016,302.0,21.00,3017.0,13.0,33.0,11201.0,75,84.0,36.0,1000.0,3.0,2.0,1,33,0,50,10.0,0.0,134988.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,490.50,275.33,0.0,0.00,0.0,0,5.0,5.0,1571850.0,1571850.0,1571850.0,1571850.0,0.0,0.0,0.0,0.00,7.20,2.0,6.5,3.000540e+09,0.0,21.0,988208.0,195011.0,1,73,30101.0,3.000540e+09,0.0,1559.889144,140131.577176
1,8,23,8,204,1,104,11201,0,0,0,32000.0,304650.0,1924,4,105,340000000.0,4850,2016,302.0,1.00,1003.0,13.0,33.0,11201.0,2,84.0,38.0,2300.0,3.0,2.0,0,45,0,106,5.0,0.0,32000.0,304650.0,304650.0,0.0,264750.0,0.0,0.0,0.0,0.0,39900.0,2.0,1.0,13.0,0.0,0.0,92.42,335.92,335.0,92.00,0.0,1,3.0,5.0,1548000.0,25463250.0,0.0,0.0,1924.0,1980.0,0.0,9.52,0.00,2.0,0.0,3.002040e+09,0.0,1.0,985952.0,195007.0,1,61,30106.0,0.000000e+00,0.0,890.718521,34656.447240
2,42,25,8,8470,55,81,11234,0,123,123,905000.0,2548000.0,1970,4,82,276947000.0,3544,2012,318.0,698.00,2005.0,22.0,46.0,11234.0,58,63.0,35.0,8822.0,3.0,18.0,21,46,0,83,5.0,1.0,905000.0,2548000.0,2548000.0,0.0,0.0,1263000.0,1285000.0,0.0,0.0,0.0,2.0,4.0,2.0,0.0,123.0,930.00,859.00,0.0,0.00,0.0,1,3.0,5.0,36532350.0,149792400.0,0.0,0.0,1970.0,0.0,0.0,2.82,0.00,2.0,0.0,3.084700e+09,0.0,698.0,1006597.0,161424.0,20,1518,32502.0,0.000000e+00,0.0,3729.786857,797554.847834
3,8,31,8,230,1,62,11201,0,1,1,20267.0,356000.0,1927,4,61,202500000.0,5288,2017,302.0,3.01,2000.0,13.0,33.0,11201.0,2,84.0,38.0,2300.0,3.0,2.0,0,64,0,59,8.0,0.0,20267.0,356000.0,30000.0,0.0,30000.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,15.0,0.0,1.0,202.00,100.33,202.0,100.33,0.0,0,3.0,2.0,2250000.0,27166050.0,2250000.0,27166050.0,1927.0,1998.0,2000.0,17.57,2.43,0.0,4.8,3.002300e+09,0.0,301.0,985622.0,193713.0,1,71,30106.0,0.000000e+00,0.0,620.761169,21360.147631
4,59,38,8,2428,1,141,11249,0,0,0,57600.0,0.0,0,4,145,185445000.0,3498,2012,301.0,551.00,1009.0,14.0,33.0,11249.0,13,90.0,30.0,400.0,3.0,1.0,6,64,0,30,4.0,0.0,57600.0,382746.0,11200.0,371546.0,1822.0,9378.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,522.0,525.0,180.00,320.00,179.0,315.00,0.0,0,3.0,5.0,3110400.0,5579990.0,0.0,0.0,2015.0,0.0,0.0,6.64,2.43,0.0,4.8,3.024280e+09,0.0,551.0,993500.0,199202.0,1,125,30806.0,0.000000e+00,0.0,1006.337999,58564.864312

In [96]:
from sklearn.preprocessing import StandardScaler # загружаем класс для маштабирования

scal = StandardScaler()
bsm_C_n = bsm_C.drop("sale_price", axis = 1)
names = bsm_C_n.columns
bsm_C_scal = scal.fit_transform(bsm_C.drop("sale_price", axis = 1))
bsm_C_scal_w = pd.DataFrame(bsm_C_scal, columns = names)
bsm_C_scal_w

,block,lot,building_class,residential_units,commercial_units,gross_sqft,tax_class_at_sale,sale_date,PolicePrct,HealthArea,ZoneDist1,BldgArea,OfficeArea,RetailArea,UnitsRes,LotFront,LotDepth,AssessLand,ExemptTot,CommFAR,SHAPE_Area
0,-1.731731,-0.438598,0.713744,-0.244893,-0.102388,-0.233296,3.075508,1.560522,1.409747,-1.846756,-2.511459,-0.289208,-0.037067,-0.078690,-0.276852,4.400607,2.593807,2.028507,0.978024,2.276978,4.219559
1,-1.673391,-0.438598,2.145561,-0.244893,-0.102388,19.031818,3.075508,1.479481,1.409747,-1.342198,-1.390680,3.442194,61.902327,-0.078690,-0.276852,0.395712,3.542633,1.995161,-0.053178,2.276978,0.834715
2,1.541492,0.026553,1.512257,-0.244893,65.985207,160.894260,3.075508,0.677661,-1.022851,1.189134,-1.297282,30.919105,-0.037067,362.205266,-0.276852,8.822208,11.733951,50.907823,-0.053178,2.276978,25.317186
3,-1.663279,-0.438598,0.989093,-0.244893,0.434909,22.279031,3.075508,1.748391,1.409747,-1.342198,0.383887,4.071137,6.981562,-0.078690,-0.276852,1.498145,-0.146654,2.976648,17.768940,-0.188977,0.408018
4,-0.808414,-0.438598,3.164354,-0.244893,-0.102388,-0.233296,3.075508,0.649419,2.104775,-2.079629,0.383887,4.398726,0.389198,2.611333,6.267430,1.276813,3.293330,4.179599,-0.053178,-0.188977,1.601969
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303723,-0.480936,0.052395,0.768814,-0.244893,2.046802,-0.181126,3.075508,-0.774333,1.293909,-0.954076,0.383887,-0.279103,-0.037067,-0.078690,-0.276852,-0.202084,-1.326306,-0.143977,-0.053178,-0.188977,-0.245711
303724,-0.441655,-0.266320,0.768814,-0.244893,4.195992,-0.132117,3.075508,-0.762054,1.293909,-0.954076,0.383887,-0.269611,-0.037067,-0.078690,-0.276852,-0.332871,-0.465018,-0.128877,-0.053178,-0.188977,-0.222983
303725,-0.454878,-0.283548,-0.360119,0.020410,-0.102388,0.013328,3.075508,-0.663822,1.293909,-0.954076,0.383887,-0.241440,-0.037067,-0.078690,-0.239241,-0.282568,-0.277100,-0.156953,-0.053178,-0.188977,-0.197195
303726,-0.454878,-0.283548,-0.360119,0.020410,-0.102388,0.013328,3.075508,-0.805644,1.293909,-0.954076,0.383887,-0.241440,-0.037067,-0.078690,-0.239241,-0.282568,-0.277100,-0.156953,-0.053178,-0.188977,-0.197195
303727,-0.477047,-0.016516,3.797658,-0.244893,-0.102388,-0.233296,3.075508,-0.735040,1.293909,-0.954076,0.383887,-0.289208,-0.037067,-0.078690,-0.276852,-0.181963,-0.480677,-0.106228,-0.053178,-0.188977,-0.187741

In [97]:
bsm_C_test = bsm_C.drop("sale_price", axis = 1)

x = bsm_C_scal_w.copy() # копируем наш датафрейм в переменную х
y = bsm_C['sale_price'] # создаем y - целевую переменную

from sklearn.model_selection import train_test_split # подгружаем функцию, которая разбивает данные случ. образом

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33)#, random_state = 1)
# разбиение данных на обучающую и проверочную выборки

y_train

54288     615000.0
226974    306500.0
257614         0.0
155240         0.0
47637     670000.0
            ...
131771     24000.0
283297         0.0
24392     985000.0
171728         0.0
280381    371136.0
Name: sale_price, Length: 203497, dtype: float64

In [98]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()

lin_reg.fit(x_train, y_train)

LinearRegression()

In [103]:
#Исследование столбцов на их значимость

coef = pd.DataFrame(lin_reg.coef_, x.columns, columns = ["coef"]).sort_values(by = "coef", ascending = False)

coef.head(30)

                            coef
gross_sqft         618446.365293
LotFront           182777.112775
CommFAR            173174.185434
sale_date          166214.521384
LotDepth           124350.590781
AssessLand         123025.335062
OfficeArea         113738.962977
ZoneDist1           91403.927370
tax_class_at_sale   88221.537485
PolicePrct          50900.555083
commercial_units    27355.070001
BldgArea            21477.711360
HealthArea          13248.753917
RetailArea           6431.402917
ExemptTot            2241.317091
lot                 -1641.363767
building_class     -18190.364345
block              -35685.383160
residential_units  -54471.397814
SHAPE_Area        -206703.081224
UnitsRes          -211413.015698

In [108]:
#сохранение данных в файл, чтобы в случае чего не приходилось считать по несколько раз одно и то же.
bsm_C.to_csv('bsm_dataC.csv')

In [109]:
bsm_C = pd.read_csv('bsm_dataC.csv')
bsm_C = bsm_C.drop(['Unnamed: 0',], axis=1)

In [111]:
bsm_C.head()

,block,lot,building_class,residential_units,commercial_units,gross_sqft,tax_class_at_sale,sale_price,sale_date,PolicePrct,HealthArea,ZoneDist1,BldgArea,OfficeArea,RetailArea,UnitsRes,LotFront,LotDepth,AssessLand,ExemptTot,CommFAR,SHAPE_Area
0,54,1,52,0,0,0.0,4,345000000.0,4982,84.0,1000.0,33,0.0,0.0,0.0,0.0,490.50,275.33,1571850.0,1571850.0,2.0,140131.577176
1,204,1,104,0,0,304650.0,4,340000000.0,4850,84.0,2300.0,45,304650.0,264750.0,0.0,0.0,92.42,335.92,1548000.0,0.0,2.0,34656.447240
2,8470,55,81,0,123,2548000.0,4,276947000.0,3544,63.0,8822.0,46,2548000.0,0.0,1263000.0,0.0,930.00,859.00,36532350.0,0.0,2.0,797554.847834
3,230,1,62,0,1,356000.0,4,202500000.0,5288,84.0,2300.0,64,356000.0,30000.0,0.0,0.0,202.00,100.33,2250000.0,27166050.0,0.0,21360.147631
4,2428,1,141,0,0,0.0,4,185445000.0,3498,90.0,400.0,64,382746.0,1822.0,9378.0,522.0,180.00,320.00,3110400.0,0.0,0.0,58564.864312

### РАЗБИЕНИЕ ДАННЫХ НА ОБУЧАЮЩУЮ И ТЕСТИРУЮЩУЮ ВЫБОРКИ
#### Необходимо определить принцип разделения данных на обучающую и тестирующую выборки. Даже если вы выбираете случайное разделение данных, необходимо обосновать выбор данного принципа.

In [112]:
bsm_C_test = bsm_C.drop("sale_price", axis = 1)

x = bsm_C_scal_w.copy() # копируем наш датафрейм в переменную х
y = bsm_C['sale_price'] # создаем y - целевую переменную

from sklearn.model_selection import train_test_split # подгружаем функцию, которая разбивает данные случ. образом

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.33)#, random_state = 1)
# разбиение данных на обучающую и проверочную выборки

y_train

166686          0.0
35900      800000.0
281529     555000.0
196207          0.0
6829      2250000.0
            ...
187229          0.0
98597      311250.0
197600          0.0
81787      420000.0
188576          0.0
Name: sale_price, Length: 203497, dtype: float64

### ПРОГНОЗИРОВАНИЕ
#### Необходимо выбрать модель прогнозирования цен на дома (sale_price), обосновать выбор модели. Необходимо обучить модель на обучающей выборке и протестировать. После тестирования необходимо оценить точность работы выбранной модели.

In [113]:
from sklearn.metrics import classification_report # загружаем метрику отчет о классификации
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_validate

##### LinearRegression

In [114]:
from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression(n_jobs = 1)

lin_reg.fit(x_train, y_train)

LinearRegression(n_jobs=1)

In [115]:
y_pred = lin_reg.predict(x_test)

In [116]:
print('Mean Absolute Error:', mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', np.sqrt(mean_squared_error(y_test, y_pred)))  
print('Root Mean Squared Error:', r2_score(y_test, y_pred))

Mean Absolute Error: 535655.1443999727
Mean Squared Error: 2219069.962721482
Root Mean Squared Error: 0.08469655463185066

##### Ridge

In [117]:
from sklearn.linear_model import Ridge

ridge = Ridge(alpha=0.1, max_iter=200)

ridge.fit(x_train, y_train)

Ridge(alpha=0.1, max_iter=200)

In [118]:
y_pred = ridge.predict(x_test)

In [119]:
print('Mean Absolute Error:', mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', np.sqrt(mean_squared_error(y_test, y_pred)))  
print('Root Mean Squared Error:', r2_score(y_test, y_pred))

Mean Absolute Error: 535655.0761381246
Mean Squared Error: 2219069.9143434274
Root Mean Squared Error: 0.0846965945410022

##### Lasso

In [120]:
from sklearn.linear_model import Lasso

Las = Lasso()

Las.fit(x_train, y_train)

Lasso()

In [121]:
y_pred = Las.predict(x_test)

In [122]:
print('Mean Absolute Error:', mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', np.sqrt(mean_squared_error(y_test, y_pred)))  
print('Root Mean Squared Error:', r2_score(y_test, y_pred))

Mean Absolute Error: 535654.5963822394
Mean Squared Error: 2219069.4133174154
Root Mean Squared Error: 0.08469700785899648